### ISSUE TITLE
Missing btn class

### ISSUE THREAD

**Issue by RichLlew182** [chrisma89/PursuitOfHobbies#18]
The buttons in the #hobby section are not being assigned the 'btn' class so we just need that to also be added for all 4 buttons as they are missing some bootstrap styling. 

This is also missing from the buttons that are being added to the my saved hobbies dropdowns. 

The start over button on the videos section is also missing the btn class.

**Comment by chrismacaroline** [comment]
btn class added to saved hobbies buttons, startover button in video section and the 4 buttons on the #hobby page
