### ISSUE TITLE
Video Section

### ISSUE THREAD

**Issue by RichLlew182** [chrisma89/PursuitOfHobbies#19]
Can we make it so that the video section gets set to display block only when the pink videos button is clicked? At the moment it's visible by default, so you will see an empty green section on the website. I can hide it with css but then clicking the button doesn't bring it back.

**Comment by chrismacaroline** [comment]
I cant see an empty green section on my end- we could work on this together?

**Comment by chrismacaroline** [comment]
fixed this- closing issue now
