### ISSUE TITLE
Amendments to the Hobby Suggestion Question

### ISSUE THREAD

**Issue by RichLlew182** [chrisma89/PursuitOfHobbies#21]
It seems that this question is only ever showing the first option from the array - 'Have you thought about'. Looks like the script is just looking at taglineArray[0]. I think we can use Math.random to get a random index each time? 

Currently the question mark after the question for the hobby suggestion has spaces before and after but I think that these spaces can be removed.

There are two taglines in the taglineArray that would not be questions so would look a bit off if they come up, these would be "We recommend X ?" and "Here is something interesting : X ?". So I think we could reword those to be questions, or alternatively we don't do questions and do them as statements instead and drop the question mark.

**Comment by chrismacaroline** [comment]
math.random was a great shout- issue fixed.
