### ISSUE TITLE
My Hobbies button above videos

### ISSUE THREAD

**Issue by RichLlew182** [chrisma89/PursuitOfHobbies#24]
When the videos are generated there is a 'My Hobbies' button that is appearing just above the heading, I think this can be removed as we now have the my hobbies button in the top right. The Figma file does have a 'New Hobby' button at the bottom next to start over but this is probably not needed, we can just keep the start over button.

**Comment by chrismacaroline** [comment]
my hobbies button- removed (commented out for now)
