### ISSUE TITLE
My nobbies button on the navbar

### ISSUE THREAD

**Issue by chrismacaroline** [chrisma89/PursuitOfHobbies#32]
Clicking the nav bar myhobbies button would take user to saved hobbies page, giving them no option to open the videos> I suggest that its best to display it only on the page where the videos are appended.

I have hidden its display on the landing page, however you can still see it faintly if the page is refreshed.

Ideally would like it removed from navbar and added as a button near the startover button beneath the videos.

**Comment by georgielill** [comment]
Are we able to append it only on the video page? that way the user will have at least one 'saved hobby', I think it works well in the top right as this is where an 'account' section would usually live on a webpage

**Comment by RichLlew182** [comment]
I think this issue is now resolved as Chrisma got the videos to load on the my hobbies page too.
