### ISSUE TITLE
Add display none to elements that appear briefly on page load

### ISSUE THREAD

**Issue by RichLlew182** [chrisma89/PursuitOfHobbies#45]
The my hobbies button in the navbar and videos section are flashing up briefly as the page loads but are then being set to display none by the javascript. We can stop this by just adding style="display: none" as inline styling in the html.

**Comment by georgielill** [comment]
I have added the style="display: none" to both 'my hobbies' buttons but may need to check if them flickering on load is gone as I couldn't see the flicker

**Comment by RichLlew182** [comment]
All good thanks Georgie
