### ISSUE TITLE
Separate certain classes into IDs

### ISSUE THREAD

**Issue by RichLlew182** [chrisma89/PursuitOfHobbies#46]
Hi Chrisma,

I was just looking at the requirements in the readme file and saw this point:

_Have a clean repository that meets quality coding standards (file structure, naming conventions, follows best practices for class/id naming conventions, indentation, quality comments, etc.)._

I noticed that some buttons/elements are being assigned classes that are only used once, so I think that these could be better as IDs. 

For example:

newhobbybtn
videosgeneratorbtn
my-hobbies
samecategoryhobbygenerator
wikipedialinkgenerator

It could also be a good idea to camel case these elements to make them a bit more readable.

The startoverbtn is used in two places so this can stay as a class, but we can camel case that too.

Any js would need to be updated to reflect the change to IDs.

And there's also the following in the my hobbies page:

savedgeneral
generalcontainer

savedsports
sportscontainer

savededucation
educationcontainer

savedcollection
collectioncontainer

savedcompetition
compeitioncontainer

savedobservation
observationcontainer

There is a section with the class of 'savedvideossection' but I think that this should be an ID to be more inline with the sections in the index file which all have IDs, something like id='savedVideos", something like that.

The my hobbies ones can just be edited in the html but we would need to update the js file to look for the new IDs instead of the classes.

**Comment by RichLlew182** [comment]
This isn't essential so we can potentially look at this if we have time to spare, will mark as closed for now

**Comment by RichLlew182** [comment]
Reopening issue as this could be good for the project requirements

**Comment by chrismacaroline** [comment]
Completed
