### ISSUE TITLE
General Dropdown bug

### ISSUE THREAD

**Issue by RichLlew182** [chrisma89/PursuitOfHobbies#49]
Hi Chrisma, I just noticed that the general drop down on the my hobbies page does not show the 'No hobbies to view yet' text if it is empty. I can see an error in the console and it seems to be related to this line, I think the '.length' just needs removing:

if(!general.length){
      generalbutton.append($("<p>").text("No hobbies to view yet").addClass("btn-yellow btn"))
    }

**Comment by chrismacaroline** [comment]
removed the length- now the "no hobbies to view yet" is working
